### ISSUE TITLE
Support for doctrine/doctrine-module ^2.1

### ISSUE THREAD

**Issue by popovserhii** [API-Skeletons/zf-doctrine-graphql#26]
I use ZF3 with `"doctrine/doctrine-orm-module": "^2.1",` which requires `"doctrine/doctrine-module":          "^2.1"`, but `api-skeletons/zf-doctrine-graphql` dependece on `doctrine/doctrine-module: ^1.2`. Have you plans in recent future add support for the newest version of `doctrine/doctrine-module`?

Here my console output:
```bash
$ composer require api-skeletons/zf-doctrine-graphql
Loading composer repositories with package information                                                                                                                                                         Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install doctrine/doctrine-module 1.2.0
    - Installation request for api-skeletons/zf-doctrine-graphql dev-master -> satisfiable by api-skeletons/zf-doctrine-graphql[dev-master].
    - Installation request for doctrine/doctrine-orm-module ^2.1 -> satisfiable by doctrine/doctrine-orm-module[2.1.0, 2.1.1, 2.1.2].
    - api-skeletons/zf-doctrine-graphql dev-master requires zfcampus/zf-doctrine-querybuilder ^1.6 -> satisfiable by zfcampus/zf-doctrine-querybuilder[1.6.0, 1.7.x-dev, 1.6.x-dev].
    - zfcampus/zf-doctrine-querybuilder 1.6.0 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0, 1.2.x-dev].
    - zfcampus/zf-doctrine-querybuilder 1.6.x-dev requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0, 1.2.x-dev].
    - zfcampus/zf-doctrine-querybuilder 1.7.x-dev requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0, 1.2.x-dev].
    - Conclusion: don't install doctrine/doctrine-module 1.2.x-dev

**Comment by TomHAnderson** [comment]
From this composer.json:
```sh
        "doctrine/doctrine-module": "^1.2 || ^2.1",
```

I think the limiting factor is in zfcampus/zf-doctrine-querybuilder and help pushing that forward to support Doctrine 2.x Zend libraries is appreciated.   What do you think?

**Comment by popovserhii** [comment]
I'm not sure I clearly understand you.
I've seen dependencies of `zfcampus/zf-doctrine-querybuilder` and other modules and many of them require `doctrine/doctrine-module: ^1.2`. I do not think it will be simply updating all of them for support `doctrine/doctrine-module: ^2.1`.

**Comment by TomHAnderson** [comment]
What I'm saying is I do not believe this module is the reason your composer locked you at 1.x for DoctrineModule.  As you can see in my previous post 2.1 is a valid version.  I think it is zf-doctrine-querybuilder which is locking the version.  Do you see that?

**Comment by popovserhii** [comment]
Yes, you are right. I did not pay attention that `zf-doctrine-graphql` works with both `"doctrine/doctrine-module": "^1.2 || ^2.1"`.
Can you as contributor of `zf-doctrine-querybuilder` add support `"doctrine/doctrine-module": "^1.2 || ^2.1"` to its `composer.json`?

**Comment by TomHAnderson** [comment]
The problem with doctrine/doctrine-module 2.1 is doctrine/doctrine-mongo-odm-module does not support it.  It's actually a big problem and I've been aware of it for some time.  I found that doctrine/mongo-odm had to be changed to get the whole chain up to speed.

If you could try running the unit tests for zf-doctrine-querybuilder to find what's blocking that it would help me getting the chain updated.

**Comment by TomHAnderson** [comment]
doctrine-mongo-odm-module now supports doctrine-module 2.1 so this should get corrected soon.
