### ISSUE TITLE
Are mutations supported ?

### ISSUE THREAD

**Issue by bertrandgauthier** [API-Skeletons/zf-doctrine-graphql#28]
Hi, and thank you for this module !
Could you tell me if mutations are supported, please ? Or planned.
And if not, do you have insights about the way to do it ?
Thanks again.

**Comment by TomHAnderson** [comment]
Hello,
I cannot define what mutations would look like.  e.g. CRUD per entity?  That's not very useful.
Can you define what you're actually asking for?  What do you think this library could provide for mutations for everyone?

I don't think there's any answer for everyone so mutations are absolutely available for you to write yourself for your needs.

**Comment by TomHAnderson** [comment]
No reply; closing

**Comment by bertrandgauthier** [comment]
Very well, thank you.
